// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: relay_control

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenHome
void ui_ScreenHome_screen_init(void);
lv_obj_t * ui_ScreenHome;
lv_obj_t * ui_ScreenHome_Container_ContainerSysName;
lv_obj_t * ui_ScreenHome_Label_LabelSysName;
lv_obj_t * ui_ScreenHome_Container_ContainerTimeSetting;
lv_obj_t * ui_ScreenHome_Container_ContainerONTime;
lv_obj_t * ui_ScreenHome_Panel_PanelOnTimeLed;
lv_obj_t * ui_ScreenHome_Label_LabelOnTime;
lv_obj_t * ui_ScreenHome_Textarea_TextAreaOnTime;
lv_obj_t * ui_ScreenHome_Container_ContainerOffTime;
lv_obj_t * ui_ScreenHome_Panel_PanelOffTimeLed;
lv_obj_t * ui_ScreenHome_Label_LabelOffTime;
lv_obj_t * ui_ScreenHome_Textarea_TextAreaOffTime;
lv_obj_t * ui_ScreenHome_Container_ContainerController;
lv_obj_t * ui_ScreenHome_Keyboard_KeyboardInput;
lv_obj_t * ui_ScreenHome_Button_ButtonController;
lv_obj_t * ui_Startevents____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenHome_screen_init();
    ui_Startevents____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenHome);
}
